<Project Sdk="Aspire.AppHost.Sdk/13.5.3">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>simplestore-learning-apphost-75e07c1d-3a99-4efa-8249-6369499b767a</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SimpleStore.Identity.API/SimpleStore.Identity.API.csproj" />
    <ProjectReference Include="../SimpleStore.Catalog.API/SimpleStore.Catalog.API.csproj" />
    <ProjectReference Include="../SimpleStore.Order.API/SimpleStore.Order.API.csproj" />
    <ProjectReference Include="../SimpleStore.Cart.API/SimpleStore.Cart.API.csproj" />
    <ProjectReference Include="../SimpleStore.Inventory.API/SimpleStore.Inventory.API.csproj" />
    <ProjectReference Include="../SimpleStore.Payment.API/SimpleStore.Payment.API.csproj" />
    <ProjectReference Include="../SimpleStore.Checkout.API/SimpleStore.Checkout.API.csproj" />
    <ProjectReference Include="../SimpleStore.Gateway/SimpleStore.Gateway.csproj" />
    <ProjectReference Include="../SimpleStore.Web/SimpleStore.Web.csproj" />
    <ProjectReference Include="../SimpleStore.Admin/SimpleStore.Admin.csproj" />
  </ItemGroup>
</Project>
